apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: react-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/kapilnagi007/June-StaticWebsiteHost.git
    targetRevision: main
    path: june-batch-cicd/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true